"""unforeign ids

Revision ID: 6b144bdfac57
Revises: acee9ffbca0b
Create Date: 2025-11-23 06:35:25.374617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b144bdfac57'
down_revision: Union[str, Sequence[str], None] = 'acee9ffbca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('player_activity_mapset_id_fkey'), 'player_activity', type_='foreignkey')
    op.drop_constraint(op.f('player_activity_map_id_fkey'), 'player_activity', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('player_activity_map_id_fkey'), 'player_activity', 'beatmaps', ['map_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('player_activity_mapset_id_fkey'), 'player_activity', 'beatmapsets', ['mapset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
