"""initial schema

Revision ID: acee9ffbca0b
Revises: 
Create Date: 2025-11-23 06:10:26.888533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acee9ffbca0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beatmapsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.Column('language', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('favourite_count', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('main_mode', sa.Enum('osu', 'taiko', 'fruits', 'mania', name='mode'), nullable=True),
    sa.Column('pp', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('country_rank', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.Integer(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_username'), 'players', ['username'], unique=True)
    op.create_table('beatmaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beatmapset_id', sa.Integer(), nullable=True),
    sa.Column('difficulty_name', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.Enum('osu', 'taiko', 'fruits', 'mania', name='mode'), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('cs', sa.Float(), nullable=True),
    sa.Column('ar', sa.Float(), nullable=True),
    sa.Column('od', sa.Float(), nullable=True),
    sa.Column('hp', sa.Float(), nullable=True),
    sa.Column('star_rating', sa.Float(), nullable=True),
    sa.Column('total_length', sa.Integer(), nullable=True),
    sa.Column('hit_object_count', sa.Integer(), nullable=True),
    sa.Column('approved_date', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['beatmapset_id'], ['beatmapsets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_beatmaps_beatmapset', 'beatmaps', ['beatmapset_id'], unique=False)
    op.create_index('ix_beatmaps_bpm', 'beatmaps', ['bpm'], unique=False)
    op.create_index('ix_beatmaps_mode', 'beatmaps', ['mode'], unique=False)
    op.create_index('ix_beatmaps_star', 'beatmaps', ['star_rating'], unique=False)
    op.create_table('player_activity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('score', 'FAVOURITE', 'pinned', 'nominated', name='playeractivitytype'), nullable=True),
    sa.Column('map_id', sa.BigInteger(), nullable=True),
    sa.Column('mapset_id', sa.BigInteger(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['beatmaps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mapset_id'], ['beatmapsets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_activity_player_id'), 'player_activity', ['player_id'], unique=False)
    op.create_index('ix_player_activity_player_type_map_mapset', 'player_activity', ['player_id', 'type', 'map_id', 'mapset_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_player_activity_player_type_map_mapset', table_name='player_activity')
    op.drop_index(op.f('ix_player_activity_player_id'), table_name='player_activity')
    op.drop_table('player_activity')
    op.drop_index('ix_beatmaps_star', table_name='beatmaps')
    op.drop_index('ix_beatmaps_mode', table_name='beatmaps')
    op.drop_index('ix_beatmaps_bpm', table_name='beatmaps')
    op.drop_index('ix_beatmaps_beatmapset', table_name='beatmaps')
    op.drop_table('beatmaps')
    op.drop_index(op.f('ix_players_username'), table_name='players')
    op.drop_table('players')
    op.drop_table('beatmapsets')
    # ### end Alembic commands ###
